### ISSUE TITLE
Crash at startup: System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by EvgenyMosk** [MrNails/Coursework_3_course#1]
Just cloned a project and tried to launch it.

System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'D:\Projects\Coursework_3_course-master\HotelManagerSimulator\bin\Debug\Resource\Image\Background_field.jfif'.'

I think you need to include these files to GitHub repo as well.

**Comment by MrNails** [comment]
I added resource. This bug must be fixed.
